### ISSUE TITLE
Release doesn't include submodules?

### ISSUE THREAD

**Issue by corbett5** [LLNL/CHAI#160]
When building CHAI from the release tarball I get the following error
```
CMake Error at CMakeLists.txt:62 (message):
        The BLT submodule is not present.
```

**Comment by davidbeckingsale** [comment]
Auto-generate tarballs never include submodules. DId you try this one: https://github.com/LLNL/CHAI/releases/download/v2.2.1/chai-2.2.1.tar.gz ?

**Comment by corbett5** [comment]
Wow I think I must have selected the source code link by accident. My bad.

**Comment by corbett5** [comment]
Now I get the following error
```
CMake Error at src/tpl/umpire/src/umpire/tpl/CMakeLists.txt:104 (add_subdirectory):
  The source directory

    /usr/WS2/corbett5/thirdPartyLibs/build-quartz-clang@10.0.0-release/chai/src/chai/src/tpl/umpire/src/umpire/tpl/camp
```
Which I don't get if I create a tarball from a clone.

**Comment by mcfadden8** [comment]
That’s strange.  I just double-checked the umpire tarball and that directory seems to be there:

$ wget https://github.com/LLNL/Umpire/releases/download/v4.1.2/umpire-4.1.2.tar.gz
$ tar xf umpire-4.1.2.tar.gz
$ ls umpire-4.1.2/src/umpire/tpl/camp
CMakeLists.txt  LICENSE  NOTICE  README.md  appveyor.yml  cmake  docs  extern  include  scripts  test

Marty
On Oct 8, 2020, at 11:13 AM, Ben Corbett <notifications@github.com<mailto:notifications@github.com>> wrote:



Now I get the following error

CMake Error at src/tpl/umpire/src/umpire/tpl/CMakeLists.txt:104 (add_subdirectory):
  The source directory

    /usr/WS2/corbett5/thirdPartyLibs/build-quartz-clang@10.0.0-release/chai/src/chai/src/tpl/umpire/src/umpire/tpl/camp


Which I don't get if I create a tarball from a clone.

**Comment by corbett5** [comment]
Ahh but I get this from the Umpire submodule in CHAI.

**Comment by davidbeckingsale** [comment]
> Ahh but I get this from the Umpire submodule in CHAI.

I'm uploading a new tarball now.

**Comment by davidbeckingsale** [comment]
@corbett5 - please try the new tarball, this was related to "recursive" submodules 😬
