### ISSUE TITLE
Umpire memory sanitizer issue with 2.2.1 and clang 9 on Lassen

### ISSUE THREAD

**Issue by corbett5** [LLNL/CHAI#161]
When using `/usr/tce/packages/clang/clang-upstream-2019.03.26/bin/clang++` to build the 2.2.1 release on Lassen I get the following error
```
/usr/WS1/geosadmn/geosx/thirdPartyLibs/build-lassen-clang@upstream-release/chai/src/chai/src/tpl/umpire/src/umpire/util/memory_sanitizers.hpp:28:10: fatal error: 'sanitizer/asan_interface.h' file not found
#include <sanitizer/asan_interface.h>
```

I think this was fixed in a more recent version of Umpire, and develop builds fine.

I'm updating the GEOSX tpls and it would be nice to be able to point to a CHAI release instead of a commit off of develop.

**Comment by davidbeckingsale** [comment]
A newer compiler will probably work fine, and yes it was fixed in a later release. I can do another release of CHAI if you like?

**Comment by corbett5** [comment]
Yeah we need to update our clang compiler on Lassen and it should be easy but I'd rather not do it now. If it's just a matter of us using an older compiler then I'm happy to stick with the develop commit and move to either the 2.2.1 release or whatever is latest when we update.
