### ISSUE TITLE
Configure fails to recognize external Camp built with Raja: The following imported targets are referenced, but are missing: blt::openmp

### ISSUE THREAD

**Issue by barracuda156** [LLNL/CHAI#231]
Obviously we do not need to build `camp` twice and create a conflict at installation, however passing `-Dcamp_DIR=` fails to work:
```
CMake Error at src/tpl/umpire/src/tpl/CMakeLists.txt:106 (find_package):
  Found package configuration file:

    /opt/local/lib/cmake/camp/campConfig.cmake

  but it set camp_FOUND to FALSE so package "camp" is considered to be NOT
  FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: blt::openmp

-- Configuring incomplete, errors occurred!
```
Both `raja` and `camp` we built with OpenMP enabled. I do not understand what else it wants.

Can it be fixed and perhaps made more transparent?

**Comment by davidbeckingsale** [comment]
Umpire needs to be built with OpenMP enabled. We are working on addressing these configuration wrinkles

**Comment by adayton1** [comment]
This should be fixed now.
