### ISSUE TITLE
build failure on LC toss3 machines

### ISSUE THREAD

**Issue by rrsettgast** [LLNL/CHAI#60]
When using the umpire host-config to build chai, i get an error.

The command:
```
cmake -C ../src/tpl/umpire/host-configs/toss_3_x86_64_ib/clang_4_0_0.cmake ..
```
gives:
```
CMake Error at blt/cmake/thirdparty/SetupCUDA.cmake:6 (enable_language):
  The CMAKE_CUDA_COMPILER:

    /usr/tce/packages/cuda/cuda-9.1.85/bin/nvcc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  blt/cmake/thirdparty/SetupThirdParty.cmake:77 (include)
  blt/SetupBLT.cmake:100 (include)
  CMakeLists.txt:102 (include)


-- Configuring incomplete, errors occurred!
See also "/g/g15/settgast/workspace/Codes/geosx/CHAI/build-quartz/CMakeFiles/CMakeOutput.log".
See also "/g/g15/settgast/workspace/Codes/geosx/CHAI/build-quartz/CMakeFiles/CMakeError.log".
```
If disable cuda, I get the following error:
```
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_COMPILE_WHOLE_COMPILATION
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_DEVICE_LINK_EXECUTABLE
-- Generating done
-- Build files have been written to: /g/g15/settgast/workspace/Codes/geosx/CHAI/build-quartz
```
I get this last error on many platforms using various hostconfigs. The August20 snapshot doesn't have these problems.

**Comment by rhornung67** [comment]
@rrsettgast it looks like you're using a host-config for a toss3 machine with GPUs - I think rzhasgpu is the only machine we have for this. What platform are you trying to build on? Maybe try a different host-config?

**Comment by rrsettgast** [comment]
@rhornung67 You are correct. The first part of the issue is to point out that the toss3 hostconfigs for chai/umpire include CUDA by default.

The second part of the issue is the real problem. I get the
```
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_COMPILE_WHOLE_COMPILATION
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_DEVICE_LINK_EXECUTABLE
```
for LC, and when I try to do the GEOSX docker builds for Travis...and on my mac. Any suggestions about that issue?

**Comment by rhornung67** [comment]
It looks like different scripts are used to drive the host-config files in Umpire depending on the platform. Does it work to add '-DENABLE_CUDA=Off' as an argument to CMake when you build?

**Comment by rrsettgast** [comment]
nope. `-DENABLE_CUDA=Off` is exactly what I do to produce the error on quartz.

**Comment by davidbeckingsale** [comment]
@rrsettgast what CMake version are you using? It seems like the option is getting set properly. Can you paste the command like you are using when you call CMake?

**Comment by rrsettgast** [comment]
@davidbeckingsale The command I am using on LC is:
```
cmake -C ../src/tpl/umpire/host-configs/toss_3_x86_64_ib/clang_4_0_0.cmake -DENABLE_CUDA:BOOL=OFF
```
cmake 3.9.3 on LC, 3.11.4 on Mac, 3.13.3 on Centos7.5.
The command is a little different on the non-LC platforms, but the same error happens on all of these. And it doesn't happen with develop from August 20.

**Comment by davidbeckingsale** [comment]
What happens if you put -DENABLE_CUDA=Off before the cache file?

Can you also check your CMakeCache and check what the values of all the CUDA-related variables are?

**Comment by rrsettgast** [comment]
Moving the `-DENABLE_CUDA=Off` didn't help

The CUDA_PATH, COMPILER were set but ENABLE_CUDA was off. I removed the `include(${CMAKE_CURRENT_LIST_DIR}/cudatoolkit_9_1.cmake)` in clang_4_0_0.cmake and the problem persists.

**Comment by davidbeckingsale** [comment]
You can build this release with `-DENABLE_EXAMPLES=Off`, or use the branch in PR #61
